name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python (optional, if you need it for any processing)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Hugging Face CLI
      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      # Login to Hugging Face
      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      # Deploy to Hugging Face Spaces
      - name: Deploy to Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Replace YOUR_USERNAME and YOUR_SPACE_NAME with your actual values
          huggingface-cli upload Johnson789/Johnson789/News-Summarizer. . --token $HF_TOKEN

     
