# .github/workflows/main.yml

name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Install hf_transfer
        run: pip install hf_transfer

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      - name: Deploy to Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: "Johnson789/News-Summarizer"  # Adjust to your actual username/space
        run: |
          export HF_HUB_ENABLE_HF_TRANSFER=1
          huggingface-cli upload $HF_SPACE_ID . . --token $HF_TOKEN --repo-type space

      - name: Deployment Success
        if: success()
        run: echo "Successfully deployed to Hugging Face Spaces!"
